### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by AndreLuna6** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-horizon#2]
[PROPUESTA DE VALOR.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-horizon/files/8122229/PROPUESTA.DE.VALOR.pdf)

**Comment by JazminloRI** [comment]
Calificación: 17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
